version: "3.7"
services:
  messages-api:
    image: "mdibaiee/aylien-messages-api:1.0"
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    networks:
      - messages

  redis:
    image: "redis:5"
    networks:
      - messages
    ports:
      - 6379:6379

networks:
  messages:
    driver: bridge
