version: "3.7"
services:
  messages-api:
    image: "gcr.io/aylien-production/api-messages-challenge:53b769a"
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    networks:
      - messages

  redis:
    image: "redis:5"
    networks:
      - messages
    ports:
      - 6379:6379

networks:
  messages:
    driver: bridge
